# # https://github.com/custom-components/alexa_media_player/wiki/Configuration#integrations-page
# alexa_media:
#   accounts:
#     - email: !secret amazon_user
#       password: !secret amazon_secret
#       url: amazon.com
