---
# The camera integration allows you to use IP cameras with Home Assistant
# This loads up my camera configurations.
#
# https://www.home-assistant.io/integrations/camera/
#
camera: !include_dir_list ../entities/cameras
