---
# The Home Assistant Cloud allows you to quickly integrate your local
# Home Assistant with various cloud services like Amazon Alexa and Google Home.
#
# https://www.home-assistant.io/integrations/cloud/
#
cloud:

  # Customize the Google Assistant integration with the Naby Casa Cloud
  google_actions:

    # Entity specific configuration for Google Assistant.
    # These are loaded from a separate directory.
    entity_config: !include_dir_merge_named ../assistants/google

    # Filters for entities to include/exclude from Google Assistant.
    # These are loaded from a separate directory.
    filter:
      include_domains:
        - light
        - cover
        - media
      exclude_entities:
        - light.garage_side_light_blue_led
        - light.sonoff_t1_2_gang_blue_led
  
    # Customize the Alexa integration with the Naby Casa Cloud
  alexa:

    # Entity specific configuration for Alexa.
    # These are loaded from a separate directory.
    entity_config: !include_dir_merge_named ../assistants/alexa

    # Filters for entities to include/exclude from Alexa.
    # These are loaded from a separate directory.
    filter:
      include_domains:
        - light
        - cover
        - media
      exclude_entities:
        - light.garage_side_light_blue_led
        - light.sonoff_t1_2_gang_blue_led