# The google_assistant integration allows you to control
# things via Google Assistant (on your mobile or tablet)
# or a Google Home device.

# https://www.home-assistant.io/components/google_assistant/

google_assistant:
  project_id: home-assistant-7f181
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
  entity_config: !include_dir_merge_named ../assistants/google
