---
# The logbook component provides a different perspective on the history of
# your house by showing all the changes that happened to your house in
# reverse chronological order.
#
# https://www.home-assistant.io/components/logbook/
#
logbook:
  exclude:
    entities:
      - cover.garage_door
      - binary_sensor.emmabedsidelight_button
      # - weather.dark_sky
      - group.outside_lights
