logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
    aiounifi: debug
    homeassistant.components.unifi: debug
    homeassistant.components.device_tracker.unifi: debug
    homeassistant.components.switch.unifi: debug