Bedroom Lights:
  name: Bedroom Lights
  entities:
    - light.bobby_bedside_light
    - light.emma_bedside_light
    - light.clayton_led
    - light.iv_led
    - light.emma_led
    - light.alison_bedside_light