All Lights:
  name: All Lights
  view: false
  entities:
    - light.bobby_bedside_light
    - light.emmabedsidelight
    - light.clayton_led
    - light.iv_led
    - light.emma_led
    - light.livingroomlight1
    - light.alibedsidelight