platform: mqtt
name: "Garage Door"
state_topic: "garage_switch_topic/cmnd/POWER2"
command_topic: "garage/cmnd/POWER1"
payload_open: "ON"
payload_close: "ON"
payload_stop: "ON"
state_open: "OFF"
state_closed: "ON"
retain: true