activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  fields:
    text:
      description: "The text you would like alexa to speak"
      example: "Would you like me to close the door?"
    event_id:
      description: "Correlation ID for event responses"
      example: example_id
    alexa_device:
      description: "Alexa device you want to trigger"
      example: media_player.bobby_s_echo_show
  sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{text}}", "event": "{{event_id}}"}'
    - service: media_player.play_media
      data_template:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: amzn1.ask.skill.6d5dbf7e-76ba-4ed7-b7b3-90853ef8e690