'1549771543801':
  alias: Turn All Lights On
  sequence:
  - data: {}
    service: automation.turn_on
    entity_id: group.all_lights
'1549771543802':
  alias: Turn All Lights Off
  sequence:
  - data: {}
    service: automation.turn_off
    entity_id: group.all_lights