---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
#
cover.garage_door:
  name: Garage Door
  aliases:
    - Garage Door
    - Door Garage
    - Door of the garage
  room: Garage