---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
#
light.living_room_light:
  name: Family Room Light
  aliases:
    - Family room light
    - family light 
    - living room light 
    - family light 
    - den light
  room: Family Room 