---
# Adds an iframe panel to the Home Assistant frontend for the EPHome add-on.
# This allows me to access ESPHome straight from Home Asssitant's UI
#
# https://www.home-assistant.io/components/panel_iframe/
#
tasmoadmin:
  title: TasmoAdmin
  icon: mdi:lightbulb-on
  url: !secret panel_iframe_tasmoadmin_url