############################################
## All outside lights ON with one switch  ##
############################################

alias: "All outside lights ON with one switch"
hide_entity: True
trigger:
  - platform: state
    entity_id: switch.garage_switch1, light.back_flood_left, light.front_porch_lights_2, light.lights_driveway_near_road
    to: "on"

action:
  - service: homeassistant.turn_on
    entity_id: group.outside_lights
