############################################
## All outside lights ON with one switch  ##
############################################

alias: "All outside lights ON with one switch"
trigger:
  - platform: state
    entity_id: switch.garage_side_light_relay_1, light.back_flood_left, light.front_porch_lights_2, light.lights_driveway_near_road
    to: "on"

action:
  - service: homeassistant.turn_on
    entity_id: group.outside_lights
