##########################################
## Lights on when Garage Door Opens     ##
##########################################

alias: 'Turn lights on when garage door opens at night'
hide_entity: True
trigger:
  - platform: state
    entity_id: cover.garage_door
    to: 'open'

condition: []

action:
  - service: light.turn_on
    entity_id: light.back_flood_left
