platform: mqtt
name: "Front Porch Lights"
state_topic: "shellies/shelly1-553AB6/relay/0"
command_topic: "shellies/shelly1-553AB6/relay/0/command"
payload_on: "on"
payload_off: "off"
payload_available: "Online"
payload_not_available: "Offline"
retain: false
unique_id: 553AB6 #mac address minus alpha