platform: mqtt
name: "Lights Front Porch"
state_topic: "shellies/shellyswitch25-BA8845/relay/1"
command_topic: "shellies/shellyswitch25-BA8845/relay/1/command"
payload_on: "on"
payload_off: "off"
payload_available: "Online"
payload_not_available: "Offline"
retain: false
unique_id: BA8845123 #mac address minus alpha