platform: mqtt
name: "Lights Driveway Near Road"
state_topic: "shellies/shellyswitch25-BA8845/relay/0"
command_topic: "shellies/shellyswitch25-BA8845/relay/0/command"
payload_on: "on"
payload_off: "off"
payload_available: "Online"
payload_not_available: "Offline"
retain: false
unique_id: BA8845 #mac address minus alpha