##########################################
## Garage Door Automations              ##
##########################################

alias: 'Is the Garage door Open at night - Checks every 30 minutes.'
trigger:
  - platform: time_pattern
    minutes: '/15'

condition:
  - condition: time
    after: '22:00:00'
  - condition: state
    entity_id: cover.garage_door
    state: open

action:
  - service: cover.close_cover
    entity_id: cover.garage_door
  - service: tts.google_translate_say
    data:
      entity_id: media_player.master_display
      message: "The garage door is open"
