##########################################
## Garage Door Automations              ##
##########################################

alias: 'Is the Garage door Open while away? - Checks every 5 minutes after we drive away.'
trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
    for: 
      minutes: 5

condition:
  - condition: state
    entity_id: group.family
    state: not_home
  - condition: state
    entity_id: cover.garage_door
    state: open

action:
  - service: cover.close_cover
    entity_id: cover.garage_door
