###########################################################
## Garage Door Automations Open Door When We Arrive      ##
###########################################################

alias: 'Open door when we arrive'
trigger:
  - platform: state
    entity_id: device_tracker.life360_alison
    to: 'home'
  - platform: state
    entity_id: device_tracker.life360_bobby
    to: 'home'
  - platform: state
    entity_id: device_tracker.life360_alison
    to: 'Home'
  - platform: state
    entity_id: device_tracker.life360_bobby
    to: 'Home'

condition:
  condition: state
  entity_id: cover.garage_door
  state: closed

action:
  service: cover.open_cover
  entity_id: cover.garage_door