# # Roku power switch doesn't come with the component.
# # Have to send curl command to access it
# #
# # https://www.reddit.com/r/homeassistant/comments/8tl2pg/turn_roku_tv_onoff/
# #

# platform: command_line
# switches:
#   #toggles office Roku TV
#   living_room_tv_power:
#     friendly_name: "Living Room TV Power"
#     command_on: "curl -X POST http://192.168.107.2:8060/keypress/PowerOn"
#     command_off: "curl -X POST http://192.168.107.2:8060/keypress/PowerOff"
#     command_state: 'curl -s GET http://192.168.107.2:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
#     value_template: '{{ value == "ON" }}'
