# Sunset & Sunrise
platform: template
sensors:
  next_sunrise:
    friendly_name: Sunrise
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M %p") }}'
  next_sunset:
    friendly_name: Sunset
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M %p") }}'
